harness:
  secured: false
  uri_role_mapping:
    - uri: /*
      roles: [ ]
  envmap:
    PRODUCTION: False
    DEBUG: True
    HTTPS: False
  notifications:
    email:
      from_email: no-reply@metacell-test.org